1 create plant
MDTue/Capstone pull request #5
Opened 2022-03-29 10:31 UTC by MDTue

Create im Front- und Backend

2022-03-29 11:03 UTC, Benet5 commented on backend/src/main/java/capstone/herbs/plants/HerbsRepository.java
> +    Optional<HerbsItem> findAllByHerbsName(String herbsName);
Wenn du nur ein Item suchst, sollte hier entweder findByID oder findByName genutzt werden. FindAll gibt ne List zurück, das kann nicht in ein Optional gepackt werden.

2022-03-29 11:03 UTC, Benet5 commented on backend/src/main/java/capstone/herbs/plants/HerbsService.java
> +public class HerbsService {
wieso nutzt du hier kein Lombok? @RequiredArgsConstructor

2022-03-29 11:12 UTC, Benet5 requested changes
Bei einem Part oben hab ich ein Kommentar gesetzt. Das kann mMn. nicht durchlaufen, schau bitte mal drauf. Ansonsten sind 27 Dateien ziemlich viel:)

2022-03-30 09:22 UTC, Droggelbecher92 requested changes
Your DB Query is not used, either fix or remove it. Otherwise good 👍

2022-03-30 09:22 UTC, Droggelbecher92 commented on backend/src/main/java/capstone/herbs/plants/HerbsController.java
> +    //private final HerbsRepository herbsRepository
```suggestion
```

Remove unused comments

2022-03-30 09:22 UTC, Droggelbecher92 commented on backend/src/main/java/capstone/herbs/plants/HerbsRepository.java
> +}
```suggestion
public interface HerbsRepository extends MongoRepository<HerbsItem, String> {
    Collection<HerbsItem> findAllByHerbsName(String herbsName);
}
```
As Bennet said, but you don't use it, so you could also delete it

2022-03-31 12:56 UTC, Droggelbecher92 approved these changes
This is fine 👍

2022-03-31 13:05 UTC, Benet5 approved these changes

2022-03-31 13:06 UTC, merged